function f=sk(u,g)
global xip xim yip yim h;
f=((u(xip,:,1)+u(:,:,1)).*g(xip,:)...
  -(u(xim,:,1)+u(:,:,1)).*g(xim,:)...
  +(u(:,yip,2)+u(:,:,2)).*g(:,yip)...
  -(u(:,yim,2)+u(:,:,2)).*g(:,yim))/(4*h);
